changelog:
  categories:
    - title: Upstream (Required Minimum Version) Upgrades
      labels:
        - upstream_upgrade
    - title: Dependency Upgrades
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
