// Generated by jextract

package com.jyuzawa.onnxruntime_extern;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor OrtLoggingFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OrtLoggingFunction$MH = RuntimeHelper.downcallHandle(
        constants$0.OrtLoggingFunction$FUNC
    );
    static final FunctionDescriptor OrtGetApiBase$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle OrtGetApiBase$MH = RuntimeHelper.downcallHandle(
        "OrtGetApiBase",
        constants$0.OrtGetApiBase$FUNC
    );
    static final FunctionDescriptor OrtThreadWorkerFn$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OrtThreadWorkerFn$MH = RuntimeHelper.downcallHandle(
        constants$0.OrtThreadWorkerFn$FUNC
    );
    static final FunctionDescriptor OrtCustomCreateThreadFn$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


